# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
